name: Node.js Package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: npm publish
        working-directory: ./packages/vue-clerk
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
